"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReportError = exports.observeAxios = exports.asyncLocalStorage = exports.APIToolkit = void 0;
const apitoolkit_1 = require("./apitoolkit");
var apitoolkit_2 = require("./apitoolkit");
Object.defineProperty(exports, "APIToolkit", { enumerable: true, get: function () { return apitoolkit_2.APIToolkit; } });
var apitoolkit_js_1 = require("apitoolkit-js");
Object.defineProperty(exports, "asyncLocalStorage", { enumerable: true, get: function () { return apitoolkit_js_1.asyncLocalStorage; } });
Object.defineProperty(exports, "observeAxios", { enumerable: true, get: function () { return apitoolkit_js_1.observeAxios; } });
Object.defineProperty(exports, "ReportError", { enumerable: true, get: function () { return apitoolkit_js_1.ReportError; } });
exports.default = apitoolkit_1.APIToolkit;
